version: "3.8"

services:
  # MongoDB service (default database)
  mongodb:
    image: mongo:8
    container_name: shield-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: shield
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  # PostgreSQL service (alternative database)
  postgres:
    image: postgres:18
    container_name: shield-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shield
      POSTGRES_USER: shield
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # gRPC Receiver with MongoDB (default configuration)
  grpc-receiver:
    build: .
    container_name: shield-grpc-receiver
    restart: unless-stopped
    environment:
      DATABASE_TYPE: mongo
      MONGO_DB: shield
      GRPC_PORT: 50051
      MONGO_URI: "mongodb://admin:password@localhost:27018/shield-database?authSource=admin"
    ports:
      - "50051:50051"
    depends_on:
      - mongodb

  # Alternative gRPC Receiver with PostgreSQL
  # Uncomment and comment out the above grpc-receiver service to use PostgreSQL
  # grpc-receiver-postgres:
  #   build: .
  #   container_name: shield-grpc-receiver-postgres
  #   restart: unless-stopped
  #   environment:
  #     DATABASE_TYPE: postgres
  #     POSTGRES_URI: postgresql://shield:password@postgres:5432/shield
  #     GRPC_PORT: 50051
  #   ports:
  #     - "50051:50051"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./.env:/app/.env

  # Example Postgres-backed gRPC Receiver (ready to use)
  grpc-receiver-postgres-example:
    build: .
    container_name: shield-grpc-receiver-postgres-example
    restart: unless-stopped
    environment:
      DATABASE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: shield
      POSTGRES_USER: shield
      POSTGRES_PASSWORD: password
      GRPC_PORT: 50051
    ports:
      - "50052:50051"
    depends_on:
      - postgres

volumes:
  mongodb_data:
  postgres_data:
