apiVersion: v1
kind: ServiceAccount
metadata:
  name: shield-receiver
  namespace: shield-receiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shield-receiver
  name: shield-receiver-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shield-receiver-rolebinding
  namespace: shield-receiver
subjects:
- kind: ServiceAccount
  name: shield-receiver
  namespace: shield-receiver
roleRef:
  kind: Role
  name: shield-receiver-role
  apiGroup: rbac.authorization.k8s.io
