name: Lint Python with Ruff

on:
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check .
