name: Test (unit + integration)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: shield
          POSTGRES_USER: shield
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U shield -d shield" --health-interval=5s --health-timeout=2s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest grpcio-tools
          # Install the package in editable mode so tests can import top-level modules
          python -m pip install -e .

      - name: Wait for Postgres
        run: |
          # Wait until Postgres is ready
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U shield -d shield && exit 0 || sleep 1
          done
          echo "Postgres did not start in time" && exit 1

      - name: Generate protos and run tests
        run: |
          # Generate Python protobuf modules if they are not checked in
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. sync_service.proto || true
          pytest -q
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: shield
          POSTGRES_USER: shield
          POSTGRES_PASSWORD: password
