name: trivy
on:
  push:
    branches:
    - main
  pull_request: null
jobs:
  build:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Build an image from Dockerfile
      run: docker build -t ghcr.io/shield-scanner/shield-receiver/shield-receiver:${{ github.sha }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.33.0
      with:
        image-ref: ghcr.io/shield-scanner/shield-receiver/shield-receiver:${{ github.sha }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL,HIGH
